language: ruby

cache: bundler 

before_install: 
  - gem update bundler
  - chmod +x ./script/cibuild
  - sudo curl https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp > /bin/git-ftp

install:
  - bundle install

script: ./script/cibuild

branches:
  only:
  - build

sudo: true

notifications:
  email: false
